/*
 *
 * Home constants
 *
 */

export const DEFAULT_ACTION = 'app/Home/DEFAULT_ACTION';

export const GET_CLIENTS_ALL_INIT = 'app/Home/GET_CLIENTS_ALL_INIT';
export const GET_CLIENTS_ALL_SUCCESS = 'app/Home/GET_CLIENTS_ALL_SUCCESS';
export const GET_CLIENTS_ALL_FAILED = 'app/Home/GET_CLIENTS_ALL_FAILED';

export const GET_CLIENTS_DATE_INIT = 'app/Home/GET_CLIENTS_DATE_INIT';
export const GET_CLIENTS_DATE_SUCCESS = 'app/Home/GET_CLIENTS_DATE_SUCCESS';
export const GET_CLIENTS_DATE_FAILED = 'app/Home/GET_CLIENTS_DATE_FAILED';

export const GET_INFO_HOME_INIT = 'app/Home/GET_INFO_HOME_INIT';
export const GET_INFO_HOME_SUCCESS = 'app/Home/GET_INFO_HOME_SUCCESS';
export const GET_INFO_HOME_FAILED = 'app/Home/GET_INFO_HOME_FAILED';

export const GET_CLIENTS_MICROWD_INIT = 'app/Home/GET_CLIENTS_MICROWD_INIT';
export const GET_CLIENTS_MICROWD_SUCCESS =
  'app/Home/GET_CLIENTS_MICROWD_SUCCESS';
export const GET_CLIENTS_MICROWD_FAILED = 'app/Home/GET_CLIENTS_MICROWD_FAILED';

export const GET_CLIENTS_MICROWD_ID_INIT =
  'app/Home/GET_CLIENTS_MICROWD_ID_INIT';
export const GET_CLIENTS_MICROWD_ID_SUCCESS =
  'app/Home/GET_CLIENTS_MICROWD_ID_SUCCESS';
export const GET_CLIENTS_MICROWD_ID_FAILED =
  'app/Home/GET_CLIENTS_MICROWD_ID_FAILED';

export const GET_CLIENTS_MICROWD_DATE_INIT =
  'app/Home/GET_CLIENTS_MICROWD_DATE_INIT';
export const GET_CLIENTS_MICROWD_DATE_SUCCESS =
  'app/Home/GET_CLIENTS_MICROWD_DATE_SUCCESS';
export const GET_CLIENTS_MICROWD_DATE_FAILED =
  'app/Home/GET_CLIENTS_MICROWD_DATE_FAILED';

export const GET_INFO_HOME_MICROWD_INIT = 'app/Home/GET_INFO_HOME_MICROWD_INIT';
export const GET_INFO_HOME_MICROWD_SUCCESS =
  'app/Home/GET_INFO_HOME_MICROWD_SUCCESS';
export const GET_INFO_HOME_MICROWD_FAILED =
  'app/Home/GET_INFO_HOME_MICROWD_FAILED';

export const GET_CLIENTS_PROGRESEMOS_INIT =
  'app/Home/GET_CLIENTS_PROGRESEMOS_INIT';
export const GET_CLIENTS_PROGRESEMOS_SUCCESS =
  'app/Home/GET_CLIENTS_PROGRESEMOS_SUCCESS';
export const GET_CLIENTS_PROGRESEMOS_FAILED =
  'app/Home/GET_CLIENTS_PROGRESEMOS_FAILED';

export const GET_CLIENTS_PROGRESEMOS_ID_INIT =
  'app/Home/GET_CLIENTS_PROGRESEMOS_ID_INIT';
export const GET_CLIENTS_PROGRESEMOS_ID_SUCCESS =
  'app/Home/GET_CLIENTS_PROGRESEMOS_ID_SUCCESS';
export const GET_CLIENTS_PROGRESEMOS_ID_FAILED =
  'app/Home/GET_CLIENTS_PROGRESEMOS_ID_FAILED';

export const GET_CLIENTS_PROGRESEMOS_DATE_INIT =
  'app/Home/GET_CLIENTS_PROGRESEMOS_DATE_INIT';
export const GET_CLIENTS_PROGRESEMOS_DATE_SUCCESS =
  'app/Home/GET_CLIENTS_PROGRESEMOS_DATE_SUCCESS';
export const GET_CLIENTS_PROGRESEMOS_DATE_FAILED =
  'app/Home/GET_CLIENTS_PROGRESEMOS_DATE_FAILED';

export const GET_INFO_HOME_PROGRESEMOS_INIT =
  'app/Home/GET_INFO_HOME_PROGRESEMOS_INIT';
export const GET_INFO_HOME_PROGRESEMOS_SUCCESS =
  'app/Home/GET_INFO_HOME_PROGRESEMOS_SUCCESS';
export const GET_INFO_HOME_PROGRESEMOS_FAILED =
  'app/Home/GET_INFO_HOME_PROGRESEMOS_FAILED';

export const GET_MENTORS_INIT = 'app/Home/GET_MENTORS_INIT';
export const GET_MENTORS_SUCCESS = 'app/Home/GET_MENTORS_SUCCESS';
export const GET_MENTORS_FAILED = 'app/Home/GET_MENTORS_FAILED';

export const GET_USERS_INIT = 'app/Home/GET_USERS_INIT';
export const GET_USERS_SUCCESS = 'app/Home/GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'app/Home/GET_USERS_FAILED';

export const GET_NOTIFICATIONS_INIT = 'app/Home/GET_NOTIFICATIONS_INIT';
export const GET_NOTIFICATIONS_SUCCESS = 'app/Home/GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILED = 'app/Home/GET_NOTIFICATIONS_FAILED';

export const GET_VIDEOS_INIT = 'app/Home/GET_VIDEOS_INIT';
export const GET_VIDEOS_SUCCESS = 'app/Home/GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAILED = 'app/Home/GET_VIDEOS_FAILED';

export const GET_COURSES_INIT = 'app/Home/GET_COURSES_INIT';
export const GET_COURSES_SUCCESS = 'app/Home/GET_COURSES_SUCCESS';
export const GET_COURSES_FAILED = 'app/Home/GET_COURSES_FAILED';
